#PROCESSING FILE :  tests/bench/test_yahoo.py bench/test_yahoo.py logs/bench_test_yahoo.log
bench/test_yahoo.py  :  
	 -ipython3 tests/bench/test_yahoo.py  >  logs/bench_test_yahoo.log  2>&1
#PROCESSING FILE :  tests/bench/test_M4_C0808_failure.py bench/test_M4_C0808_failure.py logs/bench_test_M4_C0808_failure.log
bench/test_M4_C0808_failure.py  :  
	 -ipython3 tests/bench/test_M4_C0808_failure.py  >  logs/bench_test_M4_C0808_failure.log  2>&1
#PROCESSING FILE :  tests/bench/test_M2Comp.py bench/test_M2Comp.py logs/bench_test_M2Comp.log
bench/test_M2Comp.py  :  
	 -ipython3 tests/bench/test_M2Comp.py  >  logs/bench_test_M2Comp.log  2>&1
#PROCESSING FILE :  tests/bench/test_MWH_datasets.py bench/test_MWH_datasets.py logs/bench_test_MWH_datasets.log
bench/test_MWH_datasets.py  :  
	 -ipython3 tests/bench/test_MWH_datasets.py  >  logs/bench_test_MWH_datasets.log  2>&1
#PROCESSING FILE :  tests/bench/test_stock_prices.py bench/test_stock_prices.py logs/bench_test_stock_prices.log
bench/test_stock_prices.py  :  
	 -ipython3 tests/bench/test_stock_prices.py  >  logs/bench_test_stock_prices.log  2>&1
#PROCESSING FILE :  tests/bench/test_yahoo_cac40.py bench/test_yahoo_cac40.py logs/bench_test_yahoo_cac40.log
bench/test_yahoo_cac40.py  :  
	 -ipython3 tests/bench/test_yahoo_cac40.py  >  logs/bench_test_yahoo_cac40.log  2>&1
#PROCESSING FILE :  tests/bench/test_M4Comp.py bench/test_M4Comp.py logs/bench_test_M4Comp.log
bench/test_M4Comp.py  :  
	 -ipython3 tests/bench/test_M4Comp.py  >  logs/bench_test_M4Comp.log  2>&1
#PROCESSING FILE :  tests/bench/test_M3Comp.py bench/test_M3Comp.py logs/bench_test_M3Comp.log
bench/test_M3Comp.py  :  
	 -ipython3 tests/bench/test_M3Comp.py  >  logs/bench_test_M3Comp.log  2>&1
#PROCESSING FILE :  tests/bench/test_M1Comp.py bench/test_M1Comp.py logs/bench_test_M1Comp.log
bench/test_M1Comp.py  :  
	 -ipython3 tests/bench/test_M1Comp.py  >  logs/bench_test_M1Comp.log  2>&1
#PROCESSING FILE :  tests/bench/test_MComp.py bench/test_MComp.py logs/bench_test_MComp.log
bench/test_MComp.py  :  
	 -ipython3 tests/bench/test_MComp.py  >  logs/bench_test_MComp.log  2>&1
#PROCESSING FILE :  tests/bench/test_NN5.py bench/test_NN5.py logs/bench_test_NN5.log
bench/test_NN5.py  :  
	 -ipython3 tests/bench/test_NN5.py  >  logs/bench_test_NN5.log  2>&1
#PROCESSING FILE :  tests/bench/test_NN3.py bench/test_NN3.py logs/bench_test_NN3.log
bench/test_NN3.py  :  
	 -ipython3 tests/bench/test_NN3.py  >  logs/bench_test_NN3.log  2>&1
#PROCESSING FILE :  tests/bench/test_artificial_one_dataset.py bench/test_artificial_one_dataset.py logs/bench_test_artificial_one_dataset.log
bench/test_artificial_one_dataset.py  :  
	 -ipython3 tests/bench/test_artificial_one_dataset.py  >  logs/bench_test_artificial_one_dataset.log  2>&1


 bench :  bench/test_artificial_one_dataset.py bench/test_NN3.py bench/test_NN5.py bench/test_MComp.py bench/test_M1Comp.py bench/test_M3Comp.py bench/test_M4Comp.py bench/test_yahoo_cac40.py bench/test_stock_prices.py bench/test_MWH_datasets.py bench/test_M2Comp.py bench/test_M4_C0808_failure.py bench/test_yahoo.py  
 

#PROCESSING FILE :  tests/codegen/test_air_passengers_code_gen.py codegen/test_air_passengers_code_gen.py logs/codegen_test_air_passengers_code_gen.log
codegen/test_air_passengers_code_gen.py  :  
	 -ipython3 tests/codegen/test_air_passengers_code_gen.py  >  logs/codegen_test_air_passengers_code_gen.log  2>&1
#PROCESSING FILE :  tests/codegen/test_ozone_code_gen_2.py codegen/test_ozone_code_gen_2.py logs/codegen_test_ozone_code_gen_2.log
codegen/test_ozone_code_gen_2.py  :  
	 -ipython3 tests/codegen/test_ozone_code_gen_2.py  >  logs/codegen_test_ozone_code_gen_2.log  2>&1
#PROCESSING FILE :  tests/codegen/test_air_passengers_code_gen_proto.py codegen/test_air_passengers_code_gen_proto.py logs/codegen_test_air_passengers_code_gen_proto.log
codegen/test_air_passengers_code_gen_proto.py  :  
	 -ipython3 tests/codegen/test_air_passengers_code_gen_proto.py  >  logs/codegen_test_air_passengers_code_gen_proto.log  2>&1
#PROCESSING FILE :  tests/codegen/test_random_exogenous_code_gen.py codegen/test_random_exogenous_code_gen.py logs/codegen_test_random_exogenous_code_gen.log
codegen/test_random_exogenous_code_gen.py  :  
	 -ipython3 tests/codegen/test_random_exogenous_code_gen.py  >  logs/codegen_test_random_exogenous_code_gen.log  2>&1
#PROCESSING FILE :  tests/codegen/test_ozone_code_gen.py codegen/test_ozone_code_gen.py logs/codegen_test_ozone_code_gen.log
codegen/test_ozone_code_gen.py  :  
	 -ipython3 tests/codegen/test_ozone_code_gen.py  >  logs/codegen_test_ozone_code_gen.log  2>&1
#PROCESSING FILE :  tests/codegen/test_cycle_code_gen.py codegen/test_cycle_code_gen.py logs/codegen_test_cycle_code_gen.log
codegen/test_cycle_code_gen.py  :  
	 -ipython3 tests/codegen/test_cycle_code_gen.py  >  logs/codegen_test_cycle_code_gen.log  2>&1
#PROCESSING FILE :  tests/codegen/test_lin_trend_cycle_code_gen.py codegen/test_lin_trend_cycle_code_gen.py logs/codegen_test_lin_trend_cycle_code_gen.log
codegen/test_lin_trend_cycle_code_gen.py  :  
	 -ipython3 tests/codegen/test_lin_trend_cycle_code_gen.py  >  logs/codegen_test_lin_trend_cycle_code_gen.log  2>&1
#PROCESSING FILE :  tests/codegen/test_ozone_exogenous_code_gen.py codegen/test_ozone_exogenous_code_gen.py logs/codegen_test_ozone_exogenous_code_gen.log
codegen/test_ozone_exogenous_code_gen.py  :  
	 -ipython3 tests/codegen/test_ozone_exogenous_code_gen.py  >  logs/codegen_test_ozone_exogenous_code_gen.log  2>&1
#PROCESSING FILE :  tests/codegen/test_ozone_no_seas_code_gen.py codegen/test_ozone_no_seas_code_gen.py logs/codegen_test_ozone_no_seas_code_gen.log
codegen/test_ozone_no_seas_code_gen.py  :  
	 -ipython3 tests/codegen/test_ozone_no_seas_code_gen.py  >  logs/codegen_test_ozone_no_seas_code_gen.log  2>&1


 codegen :  codegen/test_ozone_no_seas_code_gen.py codegen/test_ozone_exogenous_code_gen.py codegen/test_lin_trend_cycle_code_gen.py codegen/test_cycle_code_gen.py codegen/test_ozone_code_gen.py codegen/test_random_exogenous_code_gen.py codegen/test_air_passengers_code_gen_proto.py codegen/test_ozone_code_gen_2.py codegen/test_air_passengers_code_gen.py  
 

#PROCESSING FILE :  tests/exog/test_random_exogenous.py exog/test_random_exogenous.py logs/exog_test_random_exogenous.log
exog/test_random_exogenous.py  :  
	 -ipython3 tests/exog/test_random_exogenous.py  >  logs/exog_test_random_exogenous.log  2>&1
#PROCESSING FILE :  tests/exog/test_ozone_exogenous_profile.py exog/test_ozone_exogenous_profile.py logs/exog_test_ozone_exogenous_profile.log
exog/test_ozone_exogenous_profile.py  :  
	 -ipython3 tests/exog/test_ozone_exogenous_profile.py  >  logs/exog_test_ozone_exogenous_profile.log  2>&1
#PROCESSING FILE :  tests/exog/test_ozone_exogenous.py exog/test_ozone_exogenous.py logs/exog_test_ozone_exogenous.log
exog/test_ozone_exogenous.py  :  
	 -ipython3 tests/exog/test_ozone_exogenous.py  >  logs/exog_test_ozone_exogenous.log  2>&1


 exog :  exog/test_ozone_exogenous.py exog/test_ozone_exogenous_profile.py exog/test_random_exogenous.py  
 

#PROCESSING FILE :  tests/func/test_cycle.py func/test_cycle.py logs/func_test_cycle.log
func/test_cycle.py  :  
	 -ipython3 tests/func/test_cycle.py  >  logs/func_test_cycle.log  2>&1
#PROCESSING FILE :  tests/func/test_ozone.py func/test_ozone.py logs/func_test_ozone.log
func/test_ozone.py  :  
	 -ipython3 tests/func/test_ozone.py  >  logs/func_test_ozone.log  2>&1
#PROCESSING FILE :  tests/func/test_cycles_full.py func/test_cycles_full.py logs/func_test_cycles_full.log
func/test_cycles_full.py  :  
	 -ipython3 tests/func/test_cycles_full.py  >  logs/func_test_cycles_full.log  2>&1
#PROCESSING FILE :  tests/func/test_air_passengers.py func/test_air_passengers.py logs/func_test_air_passengers.log
func/test_air_passengers.py  :  
	 -ipython3 tests/func/test_air_passengers.py  >  logs/func_test_air_passengers.log  2>&1
#PROCESSING FILE :  tests/func/test_const_signal.py func/test_const_signal.py logs/func_test_const_signal.log
func/test_const_signal.py  :  
	 -ipython3 tests/func/test_const_signal.py  >  logs/func_test_const_signal.log  2>&1


 func :  func/test_const_signal.py func/test_air_passengers.py func/test_cycles_full.py func/test_ozone.py func/test_cycle.py  
 

#PROCESSING FILE :  tests/perf/test_perf1.py perf/test_perf1.py logs/perf_test_perf1.log
perf/test_perf1.py  :  
	 -ipython3 tests/perf/test_perf1.py  >  logs/perf_test_perf1.log  2>&1
#PROCESSING FILE :  tests/perf/test_parallel.py perf/test_parallel.py logs/perf_test_parallel.log
perf/test_parallel.py  :  
	 -ipython3 tests/perf/test_parallel.py  >  logs/perf_test_parallel.log  2>&1
#PROCESSING FILE :  tests/perf/test_ozone_long_series_2.py perf/test_ozone_long_series_2.py logs/perf_test_ozone_long_series_2.log
perf/test_ozone_long_series_2.py  :  
	 -ipython3 tests/perf/test_ozone_long_series_2.py  >  logs/perf_test_ozone_long_series_2.log  2>&1
#PROCESSING FILE :  tests/perf/test_ozone_long_series.py perf/test_ozone_long_series.py logs/perf_test_ozone_long_series.log
perf/test_ozone_long_series.py  :  
	 -ipython3 tests/perf/test_ozone_long_series.py  >  logs/perf_test_ozone_long_series.log  2>&1
#PROCESSING FILE :  tests/perf/test_ozone_debug_perf.py perf/test_ozone_debug_perf.py logs/perf_test_ozone_debug_perf.log
perf/test_ozone_debug_perf.py  :  
	 -ipython3 tests/perf/test_ozone_debug_perf.py  >  logs/perf_test_ozone_debug_perf.log  2>&1


 perf :  perf/test_ozone_debug_perf.py perf/test_ozone_long_series.py perf/test_ozone_long_series_2.py perf/test_parallel.py perf/test_perf1.py  
 

#PROCESSING FILE :  tests/real-life/test_sof_example2.py real-life/test_sof_example2.py logs/real-life_test_sof_example2.log
real-life/test_sof_example2.py  :  
	 -ipython3 tests/real-life/test_sof_example2.py  >  logs/real-life_test_sof_example2.log  2>&1
#PROCESSING FILE :  tests/real-life/test_sof_example.py real-life/test_sof_example.py logs/real-life_test_sof_example.log
real-life/test_sof_example.py  :  
	 -ipython3 tests/real-life/test_sof_example.py  >  logs/real-life_test_sof_example.log  2>&1


 real-life :  real-life/test_sof_example.py real-life/test_sof_example2.py  
 

#PROCESSING FILE :  tests/time_res/test_ozone_Daily.py time_res/test_ozone_Daily.py logs/time_res_test_ozone_Daily.log
time_res/test_ozone_Daily.py  :  
	 -ipython3 tests/time_res/test_ozone_Daily.py  >  logs/time_res_test_ozone_Daily.log  2>&1
#PROCESSING FILE :  tests/time_res/test_ozone_Weekly.py time_res/test_ozone_Weekly.py logs/time_res_test_ozone_Weekly.log
time_res/test_ozone_Weekly.py  :  
	 -ipython3 tests/time_res/test_ozone_Weekly.py  >  logs/time_res_test_ozone_Weekly.log  2>&1
#PROCESSING FILE :  tests/time_res/test_ozone_Minutely.py time_res/test_ozone_Minutely.py logs/time_res_test_ozone_Minutely.log
time_res/test_ozone_Minutely.py  :  
	 -ipython3 tests/time_res/test_ozone_Minutely.py  >  logs/time_res_test_ozone_Minutely.log  2>&1
#PROCESSING FILE :  tests/time_res/test_ozone_Secondly.py time_res/test_ozone_Secondly.py logs/time_res_test_ozone_Secondly.log
time_res/test_ozone_Secondly.py  :  
	 -ipython3 tests/time_res/test_ozone_Secondly.py  >  logs/time_res_test_ozone_Secondly.log  2>&1
#PROCESSING FILE :  tests/time_res/test_ozone_Hourly.py time_res/test_ozone_Hourly.py logs/time_res_test_ozone_Hourly.log
time_res/test_ozone_Hourly.py  :  
	 -ipython3 tests/time_res/test_ozone_Hourly.py  >  logs/time_res_test_ozone_Hourly.log  2>&1


 time_res :  time_res/test_ozone_Hourly.py time_res/test_ozone_Secondly.py time_res/test_ozone_Minutely.py time_res/test_ozone_Weekly.py time_res/test_ozone_Daily.py  
 

#PROCESSING FILE :  tests/hierarchical/test_hier_prototyping_5.py hierarchical/test_hier_prototyping_5.py logs/hierarchical_test_hier_prototyping_5.log
hierarchical/test_hier_prototyping_5.py  :  
	 -ipython3 tests/hierarchical/test_hier_prototyping_5.py  >  logs/hierarchical_test_hier_prototyping_5.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_grouped_signals_BU.py hierarchical/test_grouped_signals_BU.py logs/hierarchical_test_grouped_signals_BU.log
hierarchical/test_grouped_signals_BU.py  :  
	 -ipython3 tests/hierarchical/test_grouped_signals_BU.py  >  logs/hierarchical_test_grouped_signals_BU.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_hier_prototyping_2.py hierarchical/test_hier_prototyping_2.py logs/hierarchical_test_hier_prototyping_2.log
hierarchical/test_hier_prototyping_2.py  :  
	 -ipython3 tests/hierarchical/test_hier_prototyping_2.py  >  logs/hierarchical_test_hier_prototyping_2.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_grouped_signals_TD.py hierarchical/test_grouped_signals_TD.py logs/hierarchical_test_grouped_signals_TD.log
hierarchical/test_grouped_signals_TD.py  :  
	 -ipython3 tests/hierarchical/test_grouped_signals_TD.py  >  logs/hierarchical_test_grouped_signals_TD.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_hierarchy_AU.py hierarchical/test_hierarchy_AU.py logs/hierarchical_test_hierarchy_AU.log
hierarchical/test_hierarchy_AU.py  :  
	 -ipython3 tests/hierarchical/test_hierarchy_AU.py  >  logs/hierarchical_test_hierarchy_AU.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_hierarchy_AU_BU.py hierarchical/test_hierarchy_AU_BU.py logs/hierarchical_test_hierarchy_AU_BU.log
hierarchical/test_hierarchy_AU_BU.py  :  
	 -ipython3 tests/hierarchical/test_hierarchy_AU_BU.py  >  logs/hierarchical_test_hierarchy_AU_BU.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_hierarchy_AU_TD.py hierarchical/test_hierarchy_AU_TD.py logs/hierarchical_test_hierarchy_AU_TD.log
hierarchical/test_hierarchy_AU_TD.py  :  
	 -ipython3 tests/hierarchical/test_hierarchy_AU_TD.py  >  logs/hierarchical_test_hierarchy_AU_TD.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_hierarchy_AU_OC.py hierarchical/test_hierarchy_AU_OC.py logs/hierarchical_test_hierarchy_AU_OC.log
hierarchical/test_hierarchy_AU_OC.py  :  
	 -ipython3 tests/hierarchical/test_hierarchy_AU_OC.py  >  logs/hierarchical_test_hierarchy_AU_OC.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_hier_prototyping_1.py hierarchical/test_hier_prototyping_1.py logs/hierarchical_test_hier_prototyping_1.log
hierarchical/test_hier_prototyping_1.py  :  
	 -ipython3 tests/hierarchical/test_hier_prototyping_1.py  >  logs/hierarchical_test_hier_prototyping_1.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_hier_prototyping_4.py hierarchical/test_hier_prototyping_4.py logs/hierarchical_test_hier_prototyping_4.log
hierarchical/test_hier_prototyping_4.py  :  
	 -ipython3 tests/hierarchical/test_hier_prototyping_4.py  >  logs/hierarchical_test_hier_prototyping_4.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_grouped_signals_OC.py hierarchical/test_grouped_signals_OC.py logs/hierarchical_test_grouped_signals_OC.log
hierarchical/test_grouped_signals_OC.py  :  
	 -ipython3 tests/hierarchical/test_grouped_signals_OC.py  >  logs/hierarchical_test_grouped_signals_OC.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_hier_prototyping_3.py hierarchical/test_hier_prototyping_3.py logs/hierarchical_test_hier_prototyping_3.log
hierarchical/test_hier_prototyping_3.py  :  
	 -ipython3 tests/hierarchical/test_hier_prototyping_3.py  >  logs/hierarchical_test_hier_prototyping_3.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_grouped_prototyping_1.py hierarchical/test_grouped_prototyping_1.py logs/hierarchical_test_grouped_prototyping_1.log
hierarchical/test_grouped_prototyping_1.py  :  
	 -ipython3 tests/hierarchical/test_grouped_prototyping_1.py  >  logs/hierarchical_test_grouped_prototyping_1.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_hierarchy_AU_MO.py hierarchical/test_hierarchy_AU_MO.py logs/hierarchical_test_hierarchy_AU_MO.log
hierarchical/test_hierarchy_AU_MO.py  :  
	 -ipython3 tests/hierarchical/test_hierarchy_AU_MO.py  >  logs/hierarchical_test_hierarchy_AU_MO.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_grouped_signals_MO.py hierarchical/test_grouped_signals_MO.py logs/hierarchical_test_grouped_signals_MO.log
hierarchical/test_grouped_signals_MO.py  :  
	 -ipython3 tests/hierarchical/test_grouped_signals_MO.py  >  logs/hierarchical_test_grouped_signals_MO.log  2>&1
#PROCESSING FILE :  tests/hierarchical/test_grouped.py hierarchical/test_grouped.py logs/hierarchical_test_grouped.log
hierarchical/test_grouped.py  :  
	 -ipython3 tests/hierarchical/test_grouped.py  >  logs/hierarchical_test_grouped.log  2>&1


 hierarchical :  hierarchical/test_grouped.py hierarchical/test_grouped_signals_MO.py hierarchical/test_hierarchy_AU_MO.py hierarchical/test_grouped_prototyping_1.py hierarchical/test_hier_prototyping_3.py hierarchical/test_grouped_signals_OC.py hierarchical/test_hier_prototyping_4.py hierarchical/test_hier_prototyping_1.py hierarchical/test_hierarchy_AU_OC.py hierarchical/test_hierarchy_AU_TD.py hierarchical/test_hierarchy_AU_BU.py hierarchical/test_hierarchy_AU.py hierarchical/test_grouped_signals_TD.py hierarchical/test_hier_prototyping_2.py hierarchical/test_grouped_signals_BU.py hierarchical/test_hier_prototyping_5.py  
 


# ********************************************** 

all:  bench codegen exog func perf real-life time_res hierarchical 
	

