PYTHON=python3


test_web_traffic_commons.wikimedia.org_pyaf_default.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/commons.wikimedia.org/test_web_traffic_commons.wikimedia.org_pyaf_default.py  >  logs/test_web_traffic_commons.wikimedia.org_pyaf_default.log  2>&1
test_web_traffic_commons.wikimedia.org_pyaf_default_clean.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/commons.wikimedia.org/test_web_traffic_commons.wikimedia.org_pyaf_default_clean.py  >  logs/test_web_traffic_commons.wikimedia.org_pyaf_default_clean.log  2>&1
test_web_traffic_commons.wikimedia.org_pyaf_hierarchical_top_down.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/commons.wikimedia.org/test_web_traffic_commons.wikimedia.org_pyaf_hierarchical_top_down.py  >  logs/test_web_traffic_commons.wikimedia.org_pyaf_hierarchical_top_down.log  2>&1
test_web_traffic_commons.wikimedia.org_zero.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/commons.wikimedia.org/test_web_traffic_commons.wikimedia.org_zero.py  >  logs/test_web_traffic_commons.wikimedia.org_zero.log  2>&1


 commons.wikimedia.org :  test_web_traffic_commons.wikimedia.org_zero.py test_web_traffic_commons.wikimedia.org_pyaf_hierarchical_top_down.py test_web_traffic_commons.wikimedia.org_pyaf_default_clean.py test_web_traffic_commons.wikimedia.org_pyaf_default.py  
 

test_web_traffic_de.wikipedia.org_pyaf_default.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/de.wikipedia.org/test_web_traffic_de.wikipedia.org_pyaf_default.py  >  logs/test_web_traffic_de.wikipedia.org_pyaf_default.log  2>&1
test_web_traffic_de.wikipedia.org_pyaf_default_clean.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/de.wikipedia.org/test_web_traffic_de.wikipedia.org_pyaf_default_clean.py  >  logs/test_web_traffic_de.wikipedia.org_pyaf_default_clean.log  2>&1
test_web_traffic_de.wikipedia.org_pyaf_hierarchical_top_down.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/de.wikipedia.org/test_web_traffic_de.wikipedia.org_pyaf_hierarchical_top_down.py  >  logs/test_web_traffic_de.wikipedia.org_pyaf_hierarchical_top_down.log  2>&1
test_web_traffic_de.wikipedia.org_zero.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/de.wikipedia.org/test_web_traffic_de.wikipedia.org_zero.py  >  logs/test_web_traffic_de.wikipedia.org_zero.log  2>&1


 de.wikipedia.org :  test_web_traffic_de.wikipedia.org_zero.py test_web_traffic_de.wikipedia.org_pyaf_hierarchical_top_down.py test_web_traffic_de.wikipedia.org_pyaf_default_clean.py test_web_traffic_de.wikipedia.org_pyaf_default.py  
 

test_web_traffic_en.wikipedia.org_pyaf_default.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/en.wikipedia.org/test_web_traffic_en.wikipedia.org_pyaf_default.py  >  logs/test_web_traffic_en.wikipedia.org_pyaf_default.log  2>&1
test_web_traffic_en.wikipedia.org_pyaf_default_clean.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/en.wikipedia.org/test_web_traffic_en.wikipedia.org_pyaf_default_clean.py  >  logs/test_web_traffic_en.wikipedia.org_pyaf_default_clean.log  2>&1
test_web_traffic_en.wikipedia.org_pyaf_hierarchical_top_down.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/en.wikipedia.org/test_web_traffic_en.wikipedia.org_pyaf_hierarchical_top_down.py  >  logs/test_web_traffic_en.wikipedia.org_pyaf_hierarchical_top_down.log  2>&1
test_web_traffic_en.wikipedia.org_zero.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/en.wikipedia.org/test_web_traffic_en.wikipedia.org_zero.py  >  logs/test_web_traffic_en.wikipedia.org_zero.log  2>&1


 en.wikipedia.org :  test_web_traffic_en.wikipedia.org_zero.py test_web_traffic_en.wikipedia.org_pyaf_hierarchical_top_down.py test_web_traffic_en.wikipedia.org_pyaf_default_clean.py test_web_traffic_en.wikipedia.org_pyaf_default.py  
 

test_web_traffic_es.wikipedia.org_pyaf_default.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/es.wikipedia.org/test_web_traffic_es.wikipedia.org_pyaf_default.py  >  logs/test_web_traffic_es.wikipedia.org_pyaf_default.log  2>&1
test_web_traffic_es.wikipedia.org_pyaf_default_clean.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/es.wikipedia.org/test_web_traffic_es.wikipedia.org_pyaf_default_clean.py  >  logs/test_web_traffic_es.wikipedia.org_pyaf_default_clean.log  2>&1
test_web_traffic_es.wikipedia.org_pyaf_hierarchical_top_down.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/es.wikipedia.org/test_web_traffic_es.wikipedia.org_pyaf_hierarchical_top_down.py  >  logs/test_web_traffic_es.wikipedia.org_pyaf_hierarchical_top_down.log  2>&1
test_web_traffic_es.wikipedia.org_zero.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/es.wikipedia.org/test_web_traffic_es.wikipedia.org_zero.py  >  logs/test_web_traffic_es.wikipedia.org_zero.log  2>&1


 es.wikipedia.org :  test_web_traffic_es.wikipedia.org_zero.py test_web_traffic_es.wikipedia.org_pyaf_hierarchical_top_down.py test_web_traffic_es.wikipedia.org_pyaf_default_clean.py test_web_traffic_es.wikipedia.org_pyaf_default.py  
 

test_web_traffic_fr.wikipedia.org_pyaf_default.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/fr.wikipedia.org/test_web_traffic_fr.wikipedia.org_pyaf_default.py  >  logs/test_web_traffic_fr.wikipedia.org_pyaf_default.log  2>&1
test_web_traffic_fr.wikipedia.org_pyaf_default_clean.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/fr.wikipedia.org/test_web_traffic_fr.wikipedia.org_pyaf_default_clean.py  >  logs/test_web_traffic_fr.wikipedia.org_pyaf_default_clean.log  2>&1
test_web_traffic_fr.wikipedia.org_pyaf_hierarchical_top_down.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/fr.wikipedia.org/test_web_traffic_fr.wikipedia.org_pyaf_hierarchical_top_down.py  >  logs/test_web_traffic_fr.wikipedia.org_pyaf_hierarchical_top_down.log  2>&1
test_web_traffic_fr.wikipedia.org_zero.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/fr.wikipedia.org/test_web_traffic_fr.wikipedia.org_zero.py  >  logs/test_web_traffic_fr.wikipedia.org_zero.log  2>&1


 fr.wikipedia.org :  test_web_traffic_fr.wikipedia.org_zero.py test_web_traffic_fr.wikipedia.org_pyaf_hierarchical_top_down.py test_web_traffic_fr.wikipedia.org_pyaf_default_clean.py test_web_traffic_fr.wikipedia.org_pyaf_default.py  
 

test_web_traffic_ja.wikipedia.org_pyaf_default.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/ja.wikipedia.org/test_web_traffic_ja.wikipedia.org_pyaf_default.py  >  logs/test_web_traffic_ja.wikipedia.org_pyaf_default.log  2>&1
test_web_traffic_ja.wikipedia.org_pyaf_default_clean.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/ja.wikipedia.org/test_web_traffic_ja.wikipedia.org_pyaf_default_clean.py  >  logs/test_web_traffic_ja.wikipedia.org_pyaf_default_clean.log  2>&1
test_web_traffic_ja.wikipedia.org_pyaf_hierarchical_top_down.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/ja.wikipedia.org/test_web_traffic_ja.wikipedia.org_pyaf_hierarchical_top_down.py  >  logs/test_web_traffic_ja.wikipedia.org_pyaf_hierarchical_top_down.log  2>&1
test_web_traffic_ja.wikipedia.org_zero.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/ja.wikipedia.org/test_web_traffic_ja.wikipedia.org_zero.py  >  logs/test_web_traffic_ja.wikipedia.org_zero.log  2>&1


 ja.wikipedia.org :  test_web_traffic_ja.wikipedia.org_zero.py test_web_traffic_ja.wikipedia.org_pyaf_hierarchical_top_down.py test_web_traffic_ja.wikipedia.org_pyaf_default_clean.py test_web_traffic_ja.wikipedia.org_pyaf_default.py  
 

test_web_traffic_ru.wikipedia.org_pyaf_default.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/ru.wikipedia.org/test_web_traffic_ru.wikipedia.org_pyaf_default.py  >  logs/test_web_traffic_ru.wikipedia.org_pyaf_default.log  2>&1
test_web_traffic_ru.wikipedia.org_pyaf_default_clean.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/ru.wikipedia.org/test_web_traffic_ru.wikipedia.org_pyaf_default_clean.py  >  logs/test_web_traffic_ru.wikipedia.org_pyaf_default_clean.log  2>&1
test_web_traffic_ru.wikipedia.org_pyaf_hierarchical_top_down.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/ru.wikipedia.org/test_web_traffic_ru.wikipedia.org_pyaf_hierarchical_top_down.py  >  logs/test_web_traffic_ru.wikipedia.org_pyaf_hierarchical_top_down.log  2>&1
test_web_traffic_ru.wikipedia.org_zero.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/ru.wikipedia.org/test_web_traffic_ru.wikipedia.org_zero.py  >  logs/test_web_traffic_ru.wikipedia.org_zero.log  2>&1


 ru.wikipedia.org :  test_web_traffic_ru.wikipedia.org_zero.py test_web_traffic_ru.wikipedia.org_pyaf_hierarchical_top_down.py test_web_traffic_ru.wikipedia.org_pyaf_default_clean.py test_web_traffic_ru.wikipedia.org_pyaf_default.py  
 

test_web_traffic_www.mediawiki.org_pyaf_default.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/www.mediawiki.org/test_web_traffic_www.mediawiki.org_pyaf_default.py  >  logs/test_web_traffic_www.mediawiki.org_pyaf_default.log  2>&1
test_web_traffic_www.mediawiki.org_pyaf_default_clean.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/www.mediawiki.org/test_web_traffic_www.mediawiki.org_pyaf_default_clean.py  >  logs/test_web_traffic_www.mediawiki.org_pyaf_default_clean.log  2>&1
test_web_traffic_www.mediawiki.org_pyaf_hierarchical_top_down.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/www.mediawiki.org/test_web_traffic_www.mediawiki.org_pyaf_hierarchical_top_down.py  >  logs/test_web_traffic_www.mediawiki.org_pyaf_hierarchical_top_down.log  2>&1
test_web_traffic_www.mediawiki.org_zero.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/www.mediawiki.org/test_web_traffic_www.mediawiki.org_zero.py  >  logs/test_web_traffic_www.mediawiki.org_zero.log  2>&1


 www.mediawiki.org :  test_web_traffic_www.mediawiki.org_zero.py test_web_traffic_www.mediawiki.org_pyaf_hierarchical_top_down.py test_web_traffic_www.mediawiki.org_pyaf_default_clean.py test_web_traffic_www.mediawiki.org_pyaf_default.py  
 

test_web_traffic_zh.wikipedia.org_pyaf_default.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/zh.wikipedia.org/test_web_traffic_zh.wikipedia.org_pyaf_default.py  >  logs/test_web_traffic_zh.wikipedia.org_pyaf_default.log  2>&1
test_web_traffic_zh.wikipedia.org_pyaf_default_clean.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/zh.wikipedia.org/test_web_traffic_zh.wikipedia.org_pyaf_default_clean.py  >  logs/test_web_traffic_zh.wikipedia.org_pyaf_default_clean.log  2>&1
test_web_traffic_zh.wikipedia.org_pyaf_hierarchical_top_down.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/zh.wikipedia.org/test_web_traffic_zh.wikipedia.org_pyaf_hierarchical_top_down.py  >  logs/test_web_traffic_zh.wikipedia.org_pyaf_hierarchical_top_down.log  2>&1
test_web_traffic_zh.wikipedia.org_zero.py  :  
	 -$(PYTHON)  tests/bench/web_traffic_jobs/zh.wikipedia.org/test_web_traffic_zh.wikipedia.org_zero.py  >  logs/test_web_traffic_zh.wikipedia.org_zero.log  2>&1


 zh.wikipedia.org :  test_web_traffic_zh.wikipedia.org_zero.py test_web_traffic_zh.wikipedia.org_pyaf_hierarchical_top_down.py test_web_traffic_zh.wikipedia.org_pyaf_default_clean.py test_web_traffic_zh.wikipedia.org_pyaf_default.py  
 


# ********************************************** 

all:   commons.wikimedia.org de.wikipedia.org en.wikipedia.org es.wikipedia.org fr.wikipedia.org ja.wikipedia.org ru.wikipedia.org www.mediawiki.org zh.wikipedia.org 
	

pyaf_default:test_web_traffic_commons.wikimedia.org_pyaf_default.py test_web_traffic_de.wikipedia.org_pyaf_default.py test_web_traffic_en.wikipedia.org_pyaf_default.py test_web_traffic_es.wikipedia.org_pyaf_default.py test_web_traffic_fr.wikipedia.org_pyaf_default.py test_web_traffic_ja.wikipedia.org_pyaf_default.py test_web_traffic_ru.wikipedia.org_pyaf_default.py test_web_traffic_www.mediawiki.org_pyaf_default.py test_web_traffic_zh.wikipedia.org_pyaf_default.py
	

pyaf_hierarchical_top_down:test_web_traffic_commons.wikimedia.org_pyaf_hierarchical_top_down.py test_web_traffic_de.wikipedia.org_pyaf_hierarchical_top_down.py test_web_traffic_en.wikipedia.org_pyaf_hierarchical_top_down.py test_web_traffic_es.wikipedia.org_pyaf_hierarchical_top_down.py test_web_traffic_fr.wikipedia.org_pyaf_hierarchical_top_down.py test_web_traffic_ja.wikipedia.org_pyaf_hierarchical_top_down.py test_web_traffic_ru.wikipedia.org_pyaf_hierarchical_top_down.py test_web_traffic_www.mediawiki.org_pyaf_hierarchical_top_down.py test_web_traffic_zh.wikipedia.org_pyaf_hierarchical_top_down.py
	

